name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for Snyk to work correctly

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle@master # Or snyk/actions/maven, snyk/actions/npm, etc.
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --fail-on=high
